import { useQuery } from "@tanstack/react-query";
import { Activity, FileSearch, GitBranch, Radar } from "lucide-react";
import { Link, useOutletContext } from "react-router-dom";
import { api } from "../lib/api";
import { formatDuration, formatTimestamp, shortenCommit } from "../lib/utils";
import type { Project } from "../types/domain";
import { EmptyState, ErrorState, Metric, Panel, PanelHeader, SeverityBadge, Spinner } from "../components/ui";

export function OverviewPage() {
  const project = useOutletContext<Project>();
  const summary = useQuery({ queryKey: ["dashboard", project.id], queryFn: () => api.dashboard(project.id) });
  const scans = useQuery({ queryKey: ["scan-runs", project.id, 5], queryFn: () => api.listScanRuns(project.id, 5) });
  if (summary.isLoading) return <div className="page-loading"><Spinner label="Loading project overview…" /></div>;
  if (summary.error) return <ErrorState error={summary.error} />;
  const data = summary.data!;
  const severityRows = [["Critical", data.severity.critical, "critical"], ["High", data.severity.high, "high"], ["Medium", data.severity.medium, "medium"], ["Low", data.severity.low, "low"], ["Info", data.severity.info, "info"]] as const;
  return <div className="page overview-page"><header className="page-header"><div><span className="eyebrow">Project overview</span><h1>{project.name}</h1><p><GitBranch size={13} />{project.branch ?? "folder"} · {shortenCommit(project.commitHash)} · {project.primaryLanguage} · {project.fileCount.toLocaleString()} files</p></div><Link className="button button-primary" to={"/workspace/" + project.id + "/scanners"}><Activity size={15} />Run scan</Link></header><div className="overview-layout"><Panel className="overview-summary"><PanelHeader title="Security inbox" subtitle={data.lastScan ? "Latest scan: " + formatTimestamp(data.lastScan.startedAt) : "No scan has been recorded yet."} />{data.lastScan ? <><div className="metric-strip"><Metric label="New" value={data.newFindings} tone="text-high" /><Metric label="Existing" value={data.existingFindings} /><Metric label="Fixed" value={data.fixedFindings} tone="text-low" /><Metric label="Total" value={data.totalFindings} /></div><div className="severity-table">{severityRows.map(([label, count, severity]) => <div key={label}><SeverityBadge severity={severity} /><strong>{count}</strong></div>)}</div></> : <EmptyState icon={<FileSearch size={24} />} title="No findings yet" description="Run an installed scanner, import SARIF, or open the Demo Workspace." action={<Link className="button button-secondary" to={"/workspace/" + project.id + "/sarif"}>Import SARIF</Link>} />}</Panel><Panel><PanelHeader title="Categories" subtitle="Normalized Security IR categories" />{Object.keys(data.categories).length ? <div className="category-list">{Object.entries(data.categories).sort((left, right) => right[1] - left[1]).map(([category, count]) => <div key={category}><span>{category}</span><div className="bar"><i style={{ width: Math.max(8, count / Math.max(1, data.totalFindings) * 100) + "%" }} /></div><strong>{count}</strong></div>)}</div> : <EmptyState title="No category data" description="Categories appear after findings are imported or scanned." />}</Panel><Panel className="recent-scans-panel"><PanelHeader title="Recent Scan Runs" subtitle="Persistent history for comparisons and triage." actions={<Link className="button button-ghost" to={"/workspace/" + project.id + "/scans"}>View all</Link>} />{scans.data?.length ? <div className="scan-list">{scans.data.map((run) => <Link key={run.id} to={"/workspace/" + project.id + "/scans"} className="scan-row"><span className={"scan-dot status-" + run.status} /><div><strong>{run.gitBranch ?? "folder"} · {shortenCommit(run.gitCommit)}</strong><small>{formatTimestamp(run.startedAt)} · {run.scanners.length} scanners</small></div><span>{run.findingCount} findings</span><span>{formatDuration(run.durationMs)}</span></Link>)}</div> : <EmptyState icon={<Radar size={22} />} title="No scan history" description="Completed, failed, cancelled, imported, and demo runs are retained here." />}</Panel></div></div>;
}
